package main;


import javax.swing.JOptionPane;
import javax.swing.*;
import java.awt.*;

public class Emprestar_livros extends javax.swing.JFrame {

    /**
     * Creates new form Cadastro_livros_Def
     */
    public Emprestar_livros() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cadastrar_livro = new javax.swing.JPanel();
        btn_emprestar_livro = new javax.swing.JButton();
        nome_livro = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Cpf_cliente_field = new javax.swing.JTextField();
        senha_cliente_field = new javax.swing.JPasswordField();
        btn_pagina_inicial = new javax.swing.JButton();
        Bt_sair_2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(60, 62, 65));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(500, 450));

        cadastrar_livro.setBackground(new java.awt.Color(60, 62, 65));

        btn_emprestar_livro.setBackground(new java.awt.Color(51, 51, 51));
        btn_emprestar_livro.setText("Emprestar Livro");
        btn_emprestar_livro.setPreferredSize(new java.awt.Dimension(100, 30));
        btn_emprestar_livro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_emprestar_livroActionPerformed(evt);
            }
        });

        nome_livro.setBackground(new java.awt.Color(102, 102, 102));
        nome_livro.setForeground(new java.awt.Color(153, 153, 153));
        nome_livro.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        nome_livro.setText("Nome do livro");
        nome_livro.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        nome_livro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nome_livroFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nome_livroFocusLost(evt);
            }
        });
        nome_livro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nome_livroActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Emprestimo de livros");

        Cpf_cliente_field.setBackground(new java.awt.Color(102, 102, 102));
        Cpf_cliente_field.setForeground(new java.awt.Color(153, 153, 153));
        Cpf_cliente_field.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Cpf_cliente_field.setText("Cpf do cliente");
        Cpf_cliente_field.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        Cpf_cliente_field.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Cpf_cliente_fieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Cpf_cliente_fieldFocusLost(evt);
            }
        });
        Cpf_cliente_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cpf_cliente_fieldActionPerformed(evt);
            }
        });

        senha_cliente_field.setBackground(new java.awt.Color(102, 102, 102));
        senha_cliente_field.setForeground(new java.awt.Color(153, 153, 153));
        senha_cliente_field.setText("Senha do cliente");
        senha_cliente_field.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                senha_cliente_fieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                senha_cliente_fieldFocusLost(evt);
            }
        });
        senha_cliente_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senha_cliente_fieldActionPerformed(evt);
            }
        });

        btn_pagina_inicial.setBackground(new java.awt.Color(51, 51, 51));
        btn_pagina_inicial.setForeground(new java.awt.Color(255, 255, 255));
        btn_pagina_inicial.setText("Pagina inicial");
        btn_pagina_inicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pagina_inicialActionPerformed(evt);
            }
        });

        Bt_sair_2.setBackground(new java.awt.Color(51, 51, 51));
        Bt_sair_2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        Bt_sair_2.setForeground(new java.awt.Color(255, 0, 51));
        Bt_sair_2.setText("X");
        Bt_sair_2.setToolTipText("");
        Bt_sair_2.setAlignmentY(0.0F);
        Bt_sair_2.setBorderPainted(false);
        Bt_sair_2.setFocusPainted(false);
        Bt_sair_2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Bt_sair_2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        Bt_sair_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_sair_2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cadastrar_livroLayout = new javax.swing.GroupLayout(cadastrar_livro);
        cadastrar_livro.setLayout(cadastrar_livroLayout);
        cadastrar_livroLayout.setHorizontalGroup(
            cadastrar_livroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadastrar_livroLayout.createSequentialGroup()
                .addGroup(cadastrar_livroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cadastrar_livroLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_pagina_inicial)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Bt_sair_2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(cadastrar_livroLayout.createSequentialGroup()
                        .addGroup(cadastrar_livroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(cadastrar_livroLayout.createSequentialGroup()
                                .addGap(150, 150, 150)
                                .addGroup(cadastrar_livroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Cpf_cliente_field, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nome_livro, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(senha_cliente_field, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(cadastrar_livroLayout.createSequentialGroup()
                                .addGap(190, 190, 190)
                                .addComponent(btn_emprestar_livro, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(cadastrar_livroLayout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 44, Short.MAX_VALUE)))
                .addContainerGap())
        );
        cadastrar_livroLayout.setVerticalGroup(
            cadastrar_livroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cadastrar_livroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cadastrar_livroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_pagina_inicial, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bt_sair_2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(jLabel1)
                .addGap(60, 60, 60)
                .addComponent(nome_livro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Cpf_cliente_field, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(senha_cliente_field, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btn_emprestar_livro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cadastrar_livro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cadastrar_livro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_emprestar_livroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_emprestar_livroActionPerformed
        JOptionPane.showMessageDialog(this, "Clicked evt done");
    }//GEN-LAST:event_btn_emprestar_livroActionPerformed

    private void nome_livroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nome_livroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nome_livroActionPerformed

    private void nome_livroFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nome_livroFocusGained
             if(nome_livro.getText().equals("Nome do livro")){
                nome_livro.setText("");
                nome_livro.setForeground(Color.black);
            }
    }//GEN-LAST:event_nome_livroFocusGained

    private void nome_livroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nome_livroFocusLost
             if(nome_livro.getText().equals("")){
                nome_livro.setText("Nome do livro");
                nome_livro.setForeground(Color.gray);
            }
    }//GEN-LAST:event_nome_livroFocusLost

    private void Cpf_cliente_fieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Cpf_cliente_fieldFocusGained
             if(Cpf_cliente_field.getText().equals("Cpf do cliente")){
                Cpf_cliente_field.setText("");
                Cpf_cliente_field.setForeground(Color.black);
            }
    }//GEN-LAST:event_Cpf_cliente_fieldFocusGained

    private void Cpf_cliente_fieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Cpf_cliente_fieldFocusLost
             if(Cpf_cliente_field.getText().equals("")){
                Cpf_cliente_field.setText("Cpf do cliente");
                Cpf_cliente_field.setForeground(Color.gray);
            }
    }//GEN-LAST:event_Cpf_cliente_fieldFocusLost

    private void Cpf_cliente_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cpf_cliente_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Cpf_cliente_fieldActionPerformed

    private void btn_pagina_inicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pagina_inicialActionPerformed
        new Tela_principal().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_pagina_inicialActionPerformed

    private void Bt_sair_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_sair_2ActionPerformed
        int response = JOptionPane.showConfirmDialog(this,"Tem certeza que quer sair?", "Confirmar", JOptionPane.YES_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (response == JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_Bt_sair_2ActionPerformed

    private void senha_cliente_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senha_cliente_fieldActionPerformed
             
    }//GEN-LAST:event_senha_cliente_fieldActionPerformed

    private void senha_cliente_fieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_senha_cliente_fieldFocusGained
             if(senha_cliente_field.getText().equals("Senha do cliente")){
                senha_cliente_field.setText("");
                senha_cliente_field.setForeground(Color.black);
            }
    }//GEN-LAST:event_senha_cliente_fieldFocusGained

    private void senha_cliente_fieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_senha_cliente_fieldFocusLost
        if(senha_cliente_field.getText().equals("")){
                senha_cliente_field.setText("Senha do cliente");
                senha_cliente_field.setForeground(Color.gray);
            }
    }//GEN-LAST:event_senha_cliente_fieldFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Emprestar_livros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Emprestar_livros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Emprestar_livros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Emprestar_livros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Emprestar_livros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bt_sair_2;
    private javax.swing.JTextField Cpf_cliente_field;
    private javax.swing.JButton btn_emprestar_livro;
    private javax.swing.JButton btn_pagina_inicial;
    private javax.swing.JPanel cadastrar_livro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField nome_livro;
    private javax.swing.JPasswordField senha_cliente_field;
    // End of variables declaration//GEN-END:variables
}
